####
# R script for creating GBM paths of correlated daily asset prices. In this 
# example, we do this for Nordstrom, Microsoft and Starbucks. 
#
# November 24, 2014
####

GBM <- function(N, sigma, mu, S0, Wt = NULL) {
  # Creates a single asset path of daily prices using Geometric Brownian Motion. 
  # One year is 252 days since that is about how many trading days are in any
  # given year.
  #
  # Args:
  #   N: Number of days in the path.
  #   sigma: Volatility or standard deviation of daily continuously compounded 
  #          returns.
  #   mu: Drift or average daily continuously compounded returns. 
  #   S0: The initial price of the asset. 
  #   Wt: The cumulative Brownian motion of the model. This can be supplied or 
  #       left as NULL. In the case that it is NULL, a vector will be provided.
  #       If you include this argument, it must be a vector of length N of the 
  #       cumulative sum of a random variable to work properly. 
  #
  # Returns:
  #   A vector of length N containing the asset prices generated by the specified
  #   GBM. 
  if (is.null(Wt)) {
    Wt <- cumsum(rnorm(N, 0, 1))
  }
  t <- (1:N)/252
  p1 <- (mu - 0.5*(sigma*sigma)) * t
  p2 <- sigma * Wt
  St = S0 * exp(p1 + p2)
  return(St)
}

CorrelatedGBM <- function(N, S0, mu, sigma, cor.mat) {
  # Creates a matrix of correlated daily price paths using Geometric 
  # Brownian Motion. 
  #
  # Args: 
  #   N: Number of days in the path.
  #   mu: Drift or average daily continuously compounded returns.  
  #   sigma: Volatility or standard deviation of daily continuously compounded 
  #          returns. 
  #   S0: The initial price of the asset. 
  #   cor.mat: The correlation matrix of the daility contiuously compounded 
  #            returns. 
  #
  # Returns:
  #   A matrix of simulated daily price paths of length N having the same number
  #   of assets as in the mu and sigma vectors. Note that mu and sigma must have
  #   the same dimensions. 
  mu <- as.matrix(mu)
  sigma <- as.matrix(sigma)
  GBMs <- matrix(nrow = N, ncol = nrow(mu))
  Wt <- matrix(rnorm(N * nrow(mu), 0, 1), ncol = nrow(mu))
  Wt <- apply(Wt, 2, cumsum)
  chol.mat <- chol(cor.mat) # upper triangular cholesky decomposition
  Wt <- Wt %*% chol.mat   # key trick for creating correlated paths
  for (i in 1:nrow(mu)) {
    GBMs[,i] <- GBM(N, sigma[i], mu[i] , S0[i], Wt[, i])
  }
  return(GBMs)
}

GetPrices <- function(tickers, startDate='1992-01-02') {
  # Gets price information from Yahoo based on ticker information and the 
  # specified start date. 
  #
  # Args:
  #   tickers: A vector of the ticker symbols to download.
  #   startDate: The beginning date. Defaults to 1/2/1992.
  #
  # Returns:
  #   A zoo object with the price information. 
  prices <- get.hist.quote(instrument = tickers[1], start = startDate, 
                            quote = 'AdjClose')
  # download the rest of the prices
  for (tik in 2:length(tickers)) {
    tmp <- get.hist.quote(instrument = tickers[tik], 
                        start = start, quote = 'AdjClose')
    prices <- merge(prices, tmp)
  }
  return(prices)
}

library(zoo)
library(tseries)

set.seed(123)
N <- 4 * 252 # 4 years, each with 252 trading days
t <- (1:N)/252
start <- '2003-1-1'
tickers <- c('JWN', 'MSFT', 'SBUX')
prices <- GetPrices(tickers, start)

# get the cc returns and vectors of average returns and volaitiliy
returns.mat <- as.matrix(na.omit(diff(log(prices))))
mean.vec <- as.numeric(colMeans(returns.mat))
sigma.vec <- as.numeric(sqrt(apply(returns.mat, 2, var)))
prices.vec <- as.numeric(prices[nrow(prices)])
cor.mat <-as.matrix(cor(returns.mat))

# make correlated asset paths
paths <- CorrelatedGBM(N, prices.vec , mean.vec, sigma.vec, cor.mat)

# make a basic r plot 
colors <- c('darkblue', 'darkgreen', 'darkgoldenrod')
plot(t, paths[,1], type = 'l', ylim = c(0, max(paths)), xlab = "Year", 
     ylab = "Price", main = "Simulated Asset Prices", col = colors[1])
for (i in 2:ncol(paths)) {
  lines(t, paths[, i], col = colors[i])
}
legend(x = 0.5, y = 145, c('JWN', 'MSFT', 'SBUX'), lty = c(1,1,1), col = colors, cex = 0.7)